#!/usr/bin/env bash -e

MACHINE_NAME=codesketch

function print_jenkins_token_if_present {
	TOKEN=$(docker exec jenkins-master [ -f /var/jenkins_home/secrets/initialAdminPassword ] && cat /var/jenkins_home/secrets/initialAdminPassword)
	if [ ! -z "$TOKEN" ]; then
		echo "Jenkins unlock token: $TOKEN"
	fi
}

function configure {
	echo "Configuring Codesketch"
	docker network create codesketch
	docker-compose -f docker-compose-codesketch.yml pull
	docker-compose -f docker-compose-nginx.yml pull
	echo "... Codesketch configured"
}

function start {
	configured
	echo "Starting Codesketch in you local machine using docker compose ..."
	docker-compose -f docker-compose-codesketch.yml up -d --remove-orphans
	echo "... waiting for Codesketch to start ..."
	sleep 60s
	docker-compose -f docker-compose-nginx.yml up -d
	echo "Codesketch has started"
}

function stop {
	docker-compose -f docker-compose-codesketch.yml stop
	docker-compose -f docker-compose-nginx.yml stop
}

function clean {
	docker-compose -f docker-compose-codesketch.yml rm -f --all
	docker-compose -f docker-compose-nginx.yml rm -f --all
}

function logs {
	docker-compose -f docker-compose-codesketch.yml -f docker-compose-nginx.yml logs -f $1
}

function restart {
	docker-compose -f docker-compose-codesketch.yml -f docker-compose-nginx.yml restart $1
}

function usage {
  echo "Usage:"
  echo "    ${0} -s <stop the platform>|-u <start the platfom>|-r <redeploy the platform>"
  exit 1
}

case ${1} in
  start|stop|clean|config|logs|restart)
	case ${1} in
      start)
		start ${@:2}
	  ;;
      stop)
		stop
	  ;;
	  clean)
		clean
	  ;;
	  config)
		configure
	  ;;
	  logs)
		logs ${@:2}
	  ;;
	  restart)
		restart ${@:2}
	  ;;
	  *)
        echo "Invalid parameter(s) or option(s)."
        usage
      ;;
    esac
    exit 0
esac