version: "2"

services:

  nginx:
    restart: always
    container_name: nginx
    image: quirinobrizi/nginx:1.11.3-alpine-cs
    ports:
      - 80:80
      - 443:443
    networks:
      - codesketch
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://${LOGSTASH_HOST}:25826"
        tag: "nginx"
    env_file:
      - ./environment

networks:
  codesketch:
    external: true