version: "2"

services:
  openldap:
    image: quirinobrizi/openldap:1.1.6-cs
    restart: always
    container_name: openldap
    volumes:
      - openldap_data:/var/lib/ldap
    networks:
      - codesketch
    environment:
      LDAP_TLS: 'false'
      LDAP_READONLY_USER: 'true'
      LDAP_READONLY_USER_USERNAME: codesketch
      LDAP_READONLY_USER_PASSWORD: codesketch
    env_file:
      - ./environment
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://${LOGSTASH_HOST}:12201"
        tag: "openldap"
  
  phpopenldap:
    image: quirinobrizi/php-openldap:0.6.9-cs
    container_name: php-openldap
    ports:
      - 6443:80
    networks:
      - codesketch
    depends_on:
      - openldap
    environment:
      PHPLDAPADMIN_HTTPS: 'false'
    env_file:
      - ./environment
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://${LOGSTASH_HOST}:12201"
        tag: "phpopenldap"

networks:
  codesketch:
    external: true

volumes:
  openldap_data:
    driver: local