version: "2"

services:

  jenkins-master:
    restart: always
    container_name: jenkins-master
    image: jenkins:2.3-alpine
    expose:
      - 8080
      - 50000
    environment:
      JENKINS_OPTS: "--argumentsRealm.passwd.admin=password --prefix=/jenkins"
    volumes:
      - jenkins:/var/jenkins_home
    networks:
      - codesketch

  artifactory:
    restart: always
    container_name: artifactory
    image: mattgruter/artifactory:3.9.2
    expose:
      - 8080
    volumes:
      - artifactory-data:/artifactory/data
      - artifactory-logs:/artifactory/logs
      - artifactory-backup:/artifactory/backup
    networks:
      - codesketch

  registry:
    restart: always
    container_name: docker-registry
    image: registry:2.4.1
    expose:
      - 5000
    volumes:
      - docker-registry:/var/lib/registry
    networks:
      - codesketch

  sonarqube:
    restart: always
    container_name: sonarqube
    image: sonarqube:4.5.7-alpine
    expose: 
      - 9000
      - 9092
    environment:
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonar
      SONARQUBE_JDBC_URL: jdbc:postgresql://postgresql/sonar
    volumes:
      - ./sonarqube/sonar.properties:/opt/sonarqube/conf/sonar.properties
    depends_on:
      - postgresql
    networks:
      - codesketch

  postgresql:
    restart: always
    container_name: postgresql
    image: postgres:9.6
    expose:
      - 5432
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWOR: sonar
      POSTGRES_DB: sonar
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - codesketch

networks:
  codesketch:
    external: true

volumes:
  jenkins:
    driver: local
  artifactory-data:
    driver: local
  artifactory-logs:
    driver: local
  artifactory-backup:
    driver: local
  docker-registry:
    driver: local
  postgresql-data:
    driver: local