version: "2"

services:
  openldap:
    image: osixia/openldap:1.1.3
    restart: always
    container_name: openldap
    volumes:
      - openldap_data:/var/lib/ldap
      - ./openldap/config:/etc/ldap/slapd.d:Z
      - ./openldap/assets:/container/service/slapd/assets/
    networks:
      - codesketch
    environment:
      LDAP_TLS: 'false'
      LDAP_READONLY_USER: 'true'
      LDAP_READONLY_USER_USERNAME: codesketch
      LDAP_READONLY_USER_PASSWORD: codesketch
    env_file:
      - ./environment
  
  phpopenldap:
    image: osixia/phpldapadmin:0.6.9
    container_name: php-openldap
    ports:
      - 6443:80
    volumes:
      - ./php-openldap/environment/env.yml:/container/environment/01-custom/env.yaml
    networks:
      - codesketch
    depends_on:
      - openldap
    environment:
      PHPLDAPADMIN_HTTPS: 'false'
    env_file:
      - ./environment

networks:
  codesketch:
    external: true
volumes:
  openldap_data:
    driver: local