version: "2"

services:

  nginx:
    restart: always
    container_name: nginx
    image: quirinobrizi/nginx:1.11.6-ldap-cs
    ports:
      - 80:80
      - 443:443
    networks:
      - codesketch
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://${LOGSTASH_HOST}:12201"
        tag: "nginx"
    env_file:
      - ./environment

networks:
  codesketch:
    external: true