version: "2"

services:

  nginx:
    restart: always
    container_name: nginx
    image: nginx:1.11.0-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d/:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/public_html:/usr/share/nginx/html:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    networks:
      - codesketch

networks:
  codesketch:
    external: true