#!/usr/bin/env bash -e

docker-machine create \
	--driver virtualbox \
	--virtualbox-disk-size "5000" \
	--virtualbox-memory "768" \
	services

eval $(docker-machine env services)

docker-compose -f docker-compose-services.yml up -d

docker-machine create \
	-d virtualbox \
	--virtualbox-disk-size "5000" \
	--virtualbox-memory "1024" \
	--swarm \
	--swarm-master \
	--swarm-discovery="consul://$(docker-machine ip services):8500" \
	--engine-opt="cluster-store=consul://$(docker-machine ip services):8500" \
	--engine-opt="cluster-advertise=eth1:2376" \
	swarm-master

docker-machine create \
	-d virtualbox \
	--virtualbox-disk-size "5000" \
	--virtualbox-memory "1024" \
	--swarm \
	--swarm-discovery="consul://$(docker-machine ip services):8500" \
	--engine-opt="cluster-store=consul://$(docker-machine ip services):8500" \
	--engine-opt="cluster-advertise=eth1:2376" \
	swarm-node-01

eval $(docker-machine env --swarm swarm-master)

docker-compose -f docker-compose-apps.yml up -d