#!/bin/sh

server_name=$1
certificate=$2
certificate_key=$3
basedn=$4
admin_password=$5

echo "* configuring SSL engine, server name:${server_name}, certificate: ${certificate}, certificate key: ${certificate_key}"
mkdir -p /etc/nginx/conf.d/
mkdir -p /var/www/
rm -f /etc/nginx/conf.d/codesketch-ssl.conf
sed -e "s/%{server_name}/${server_name}/" \
  	-e "s+%{ssl_certificate}+${certificate}+" \
  	-e "s+%{ssl_certificate_key}+${certificate_key}+" \
  	/templates/codesketch-ssl.tpl.conf > /etc/nginx/conf.d/codesketch-ssl.conf
sed -e "s/%{basedn}/${basedn}/" \
	-e "s/%{password}/${admin_password}/" \
	/templates/nginx.tpl.conf > /etc/nginx/nginx.conf

nginx -g "daemon off;"
